modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="terrariamod"
version="1.0.0"
displayName="Terrariamod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Ryan Martin, MCreator"
description='''
 Terraria in Minecraft!
'''

[[dependencies.terrariamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



